### ISSUE TITLE
annotations starting 

### ISSUE THREAD

**Issue by kranthi23** [3skif9/alfresco-groupdocs-annotation-java#1]
Hi ,

From where we can start the annotations, is it from document actions or other action.Can any one clearly guide how to perform annotations.Very helpful if it done.

**Comment by 3skif9** [comment]
Hello,

Thank you for your inquiry , 

This plugin is based on the GroupDocs.Cloud service and to use it you should have an account in our service. Please investigate next links of the documentation:

- http://www.groupdocs.com/apps/annotation
- http://www.groupdocs.com/docs/display/annotation/FAQs
- http://www.groupdocs.com/docs/display/annotation/Integrating+the+Plugin+with+Alfresco+Using+Default+Method

Note: If you will need any help then please send your request to our forum - http://groupdocs.com/Community/Forums/Default.aspx


<p>Best regards,
Evgen Efimov<br>
<a href="http://groupdocs.com">http://groupdocs.com</a><br>Your Document Collaboration APIs<br>Follow us on <a href="http://www.linkedin.com/company/groupdocs">LinkedIn</a>, <a href="https://twitter.com/groupdocs">Twitter</a>, <a href="https://www.facebook.com/GroupDocsApp">Facebook</a> and <a href="https://plus.google.com/+GroupDocs">Google+</a>
